name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:       # Manual trigger

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing to branch

    steps:
      # Checkout the output branch where files will be stored
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output
          path: output

      # Generate snake graphics
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: JerryKerry
          outputs: |
            output/snake.svg
            output/snake-dark.svg?palette=github-dark
            output/snake.gif

      # Deploy generated files to output branch
      - name: Deploy to GitHub Pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output
          user_name: "GitHub Actions"
          user_email: "actions@users.noreply.github.com"
          force_orphan: true  # Keep only latest files
